### ISSUE TITLE
What happened to original Hellbound Repo?

### ISSUE THREAD

**Issue by THEG77** [GiorgioBrux/nitro-sniper-enhanced#10]

**Comment by arnavpanigrahi** [comment]
it got hacked, i guess... but this sniper is faster i guess. use this

**Comment by GiorgioBrux** [comment]
I have no idea, this is the second time it happens. Again, we are different people and I don't know him, I just forked his project. It will probably get back up soon like the last time but /shrug

**Comment by msPornHub** [comment]
> it got hacked, i guess... but this sniper is faster i guess. use this

hellbound nuked a server and he leaved github ( or changed name )
