### ISSUE TITLE
Bug is LOG related on Heroku

### ISSUE THREAD

**Issue by ItzMeAakash** [GiorgioBrux/nitro-sniper-enhanced#102]
When my friend deployed the sniper, he saw this error - 
![unknown](https://user-images.githubusercontent.com/81690524/119082272-5a7da880-ba1b-11eb-9888-2946998c8f17.png)

**Comment by GiorgioBrux** [comment]
That's probably unrelated to the sniper. Try to change region.

**Comment by nichevulcan20** [comment]
ok bro it got fixed ty sorry for late reply

**Comment by GiorgioBrux** [comment]
Nice.
