### ISSUE TITLE
[Feature request] Autojoin giveaways-related features

### ISSUE THREAD

**Issue by nichevulcan20** [GiorgioBrux/nitro-sniper-enhanced#106]
**Add a Giveaway Joiner and Host DMer. Wait lemme explain this**

- Add a timer to join giveaways like if a giveaway happens then we can join after x seconds (customizable)
- Add a feature in which if we win, we will dm the host some messages but after x seconds (customizable)
- Add a server joiner for the giveaway req feature if possible
- Add alt account support on it too, like if alt wins and gets nitro so it redeems to the main account
- Add a custom claim delay for code coming from dm from host so he doesn't feels sus and redeems to the main
- Please if u add them so pls add them for giveaway customization section
- (edit) Also add an option to send the custom response message after claiming gift from host!
- im sorry to give u work pressure

**Why we need this feature?**
Nitro drops are rarely happening on large servers. But there are soo many legit servers in which we can use this feature-rich sniper and have unlimited nitros. without messing with our main account, our alts will join and win nitros and redeem it to the main account. **bro if this is possible for u to do that then it would be EPIC!**

**but I also suggest adding these features by making a clone of your sniper (Nitro-sniper-enhanced-beta) so that this sniper won't mess up. I hope u will do that bro cuz I trust only this sniper cuz some of my friends were caught by discord by using other's snipers**

**Comment by GiorgioBrux** [comment]
Will look at these after I implement the main part of giveaway sniping (#20).

**Comment by nichevulcan20** [comment]
yes bro TYSM BRO I LOVE U BROO

**Comment by nichevulcan20** [comment]
new features

- add an optional message after the code is redeemed from host
- add sendmessage delay after code has been redeemed to main account from alt 

**please add all these features just after the improvement of the gw sniping its needed soo much cuz my friends also want this ;-;**

**Comment by ItzBoiz** [comment]
YES WE EWANT THIS PLEASE

**Comment by nichevulcan20** [comment]
hey, @GiorgioBrux I was seeing @slow's nitro-sniper, but therein issues someone was saying that the sniper disabled their account due to the **invite sniper feature** so would it be safe to add those features to this sniper cuz I trust your sniper the most because this is the point, even I saw this is real, some of my friends got disabled while using other snipers like of even @SLOW! because they say they got high pings smth like that....

**Comment by ItzBoiz** [comment]
> hey, @GiorgioBrux I was seeing @slow's nitro-sniper, but therein issues someone was saying that the sniper disabled their account due to the **invite sniper feature** so would it be safe to add those features to this sniper cuz I trust your sniper the most because this is the point, even I saw this is real, some of my friends got disabled while using other snipers like of even @slow! because they say they got high pings smth like that....

all the snipers are having risk but yes THIS sniper is super safe in my experience

**Comment by nichevulcan20** [comment]
> > hey, @GiorgioBrux I was seeing @slow's nitro-sniper, but therein issues someone was saying that the sniper disabled their account due to the **invite sniper feature** so would it be safe to add those features to this sniper cuz I trust your sniper the most because this is the point, even I saw this is real, some of my friends got disabled while using other snipers like of even @slow! because they say they got high pings smth like that....
> 
> all the snipers are having risk but yes THIS sniper is super safe in my experience

ye

**Comment by ItzBoiz** [comment]
i dont like this shit
