### ISSUE TITLE
error - tried to redeem code but the code cant be used in existing nitro subscription

### ISSUE THREAD

**Issue by nichevulcan20** [GiorgioBrux/nitro-sniper-enhanced#108]
**idk but getting these errors**
![image](https://user-images.githubusercontent.com/81959998/121568546-70402580-ca3d-11eb-90a7-907f2d5dfa4f.png)

and also when i post the code then it is weird like this
![image](https://user-images.githubusercontent.com/81959998/121568676-8fd74e00-ca3d-11eb-91dd-69ff59f01521.png)

what's this pls tell, is this a glitched gift link?

**Comment by GiorgioBrux** [comment]
It's the [epic promotion](https://www.epicgames.com/store/en-US/p/discord--discord-nitro) for 3 months free nitro. To redeem you must not have nitro now or have bought nitro in the past, which is why you can't redeem. Nothing to do with the sniper.

**Comment by nichevulcan20** [comment]
> It's the [epic promotion](https://www.epicgames.com/store/en-US/p/discord--discord-nitro) for 3 months free nitro. To redeem you must not have nitro now or have bought nitro in the past, which is why you can't redeem. Nothing to do with the sniper.

ohh ok bro thank you soo much
