### ISSUE TITLE
Tokens keep reconnecting

### ISSUE THREAD

**Issue by THEG77** [GiorgioBrux/nitro-sniper-enhanced#11]
![image](https://user-images.githubusercontent.com/48765068/94835435-8d105d80-03c6-11eb-94e6-85147f0a4379.png)
IT Keeps Doing this forever and my is causing my tokens to get locked out..... 
What might possibly be reason for this ?
I'm using 10+ slave tokens

**Comment by GiorgioBrux** [comment]
It's a weird behavior I'm investigating. Anyway, this happened even before and happens on hellbound's version too, it just doesn't print it. I will keep this issue open and see if it's the same with discord.js v12 too. 

What do you mean with "tokens to get locked out"? Do they get changed?

**Comment by THEG77** [comment]
i mean they get locked out and one has to verify by email to unlock it.

**Comment by GiorgioBrux** [comment]
That's normal behavior. 
Until I update to discord.js v12, I removed the connection errors logging so it doesn't spam the log in e6adfbd3dc670d3a42ff15c2a74a37f27a76e4aa.

**Comment by slow** [comment]
Should be fixed in `f11f102`

**Comment by GiorgioBrux** [comment]
> Should be fixed in [e866c5c](https://github.com/GiorgioBrux/nitro-sniper-enhanced/commit/e866c5c0ca51244c4a88619fdeb5020af5ee4930).

Indeed it is, thanks!
