### ISSUE TITLE
Is it safe to get 803ms pings?

### ISSUE THREAD

**Issue by ItzBoiz** [GiorgioBrux/nitro-sniper-enhanced#112]
I got 803ms ping when a code was being sniped. is this safe to have so? or shall i leave that server

**Comment by GiorgioBrux** [comment]
It's safe but it's high, if you can get a server with a better ping to discord's server then do it.

**Comment by ItzBoiz** [comment]
> It's safe but it's high, if you can get a server with a better ping to discord's server then do it.

oke so this means this was trying to redeem the code but was slow right? ahh its safe then tysm bro

**Comment by ItzBoiz** [comment]
how do i close the issue xd
