### ISSUE TITLE
[BUG] Issues related to heroku deployment

### ISSUE THREAD

**Issue by apexweeb** [GiorgioBrux/nitro-sniper-enhanced#115]
**I'm submitting a ...**
- [.] bug report
- [ ] anything else => Please do not submit support requests here. Open a discussion instead and ping me.

**I'm running**
- [.] the latest version
- [ ] anything else => Please update to the latest version and retry.

**What is the expected behavior?**
A clear and concise explanation of the expected behavior.

**What is the current behavior?**
A clear and concise explanation of the current behavior.

**Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix)
Other info if you wish.

Cant deploy to heroku 
Says "We couldn't deploy your app because the source code violates the Salesforce Acceptable Use and External-Facing Services Policy."

**Comment by ItzBoiz** [comment]
yes this is very annoying these salesforce bois aren't letting us to live happily. 
The second option is to use on replit. BUT you can only deploy the sniper to replit IF U can make private repls.

**Comment by apexweeb** [comment]
> yes this is very annoying these salesforce bois aren't letting us to live happily.
> The second option is to use on replit. BUT you can only deploy the sniper to replit IF U can make private repls.

Well isnt there ant solution to use it in heroku beacuse the other snipers have issue called "payment source required to redeem gift"

**Comment by nichevulcan20** [comment]
> > yes this is very annoying these salesforce bois aren't letting us to live happily.
> > The second option is to use on replit. BUT you can only deploy the sniper to replit IF U can make private repls.
> 
> Well isnt there any solution to use it in heroku beacuse the other snipers have issue called "payment source required to redeem gift"

Python Nitro snipers aren't banned on heroku its a good news but the developers of those snipers are inactie. also for payment methods we can use nasmo ccgen website and for checker nasmo checker and for address we can use fakeaddressgenerator

**Comment by GiorgioBrux** [comment]
I'm aware of this issue and I'm trying to find a workaround.

**Comment by nichevulcan20** [comment]
Bois just be patient. Not only this sniper is having this issue, but even other snipers which are also coded in js are having the same issue. the thing is salesforce probaly updated its tos and the snipers now violate the tos. Till then don't try other snipers on main account cuz they can be dangerous and may disable our accounts. The most trusted snipers are just from GiorgioBrux and eternal.

**Comment by GiorgioBrux** [comment]
Update: The repo has been apparently manually blacklisted, fork and then update the heroku URL to point to your repo and it will work. Instructions in readme soonTM.

**Comment by nichevulcan20** [comment]
> Update: The repo has been apparently manually blacklisted, fork and then update the heroku URL to point to your repo and it will work. Instructions in readme soonTM.

EPIC TY BRO

**Comment by apexweeb** [comment]
> Update: The repo has been apparently manually blacklisted, fork and then update the heroku URL to point to your repo and it will work. Instructions in readme soonTM.

TY

**Comment by 3w7** [comment]
for update ur fork use [Pull](https://github.com/apps/pull)

**Comment by quiet69** [comment]
still doesnt work even after forking and using this repo :( 
![image](https://user-images.githubusercontent.com/43907678/130287214-409860a6-99c1-4f57-a7df-524930fe7094.png)

**Comment by GiorgioBrux** [comment]
@quiet69 I can't find the fork on your profile. Did you delete it?

**Comment by quiet69** [comment]
@GiorgioBrux yes I deleted it :( I'll try again and send you a screenshot again tomorrow

**Comment by quiet69** [comment]
![image](https://user-images.githubusercontent.com/43907678/130367969-428d78e4-d955-4cdf-bf5f-9af0e7a85f36.png)
@GiorgioBrux

**Comment by GiorgioBrux** [comment]
@quiet69 Sorry for the delay, I thought I had answered. Your fork is also apparently blacklisted, the only thing you can do is use another github account. Maybe an org will also work, not sure.

**Comment by quiet69** [comment]
@GiorgioBrux i just downloaded your repo and added it to a new repo in my github and it worked

**Comment by quiet69** [comment]
@GiorgioBrux getting error on heroku
-----> Building on the Heroku-20 stack
-----> Determining which buildpack to use for this app
-----> Node.js app detected
       
-----> Creating runtime environment
       
       NPM_CONFIG_LOGLEVEL=error
       NODE_VERBOSE=false
       NODE_ENV=production
       NODE_MODULES_CACHE=true
       
-----> Installing binaries
       engines.node (package.json):  14.x
       engines.npm (package.json):   7.x
       
       Resolving node version 14.x...
       Downloading and installing node 14.17.5...
       Bootstrapping npm 7.x (replacing 6.14.14)...
       npm 7.x installed
       
-----> Installing dependencies
       Installing node modules
       npm ERR! code EINTEGRITY
       npm ERR! sha512-wBvR+6PacWS4QVg8+mdx6oJ8mgLpyoqRHApwxFwMByQ/9Yg02ieNBJ5zbqpzxjFJCanEtL1J4gQk91DRVS2Aag== integrity checksum failed when using sha512: wanted sha512-wBvR+6PacWS4QVg8+mdx6oJ8mgLpyoqRHApwxFwMByQ/9Yg02ieNBJ5zbqpzxjFJCanEtL1J4gQk91DRVS2Aag== but got sha512-rpVCvcO69UauZb1cruiTLzFCsWmRsn7pz8TRO2E1K2yHCRMx8kFD9UifMuQHC01T7Ot3cMmaVXE6etlLL/4q0Q==. (26256 bytes)
       
       npm ERR! A complete log of this run can be found in:
       npm ERR!     /tmp/npmcache.z0b3V/_logs/2021-08-25T12_04_54_327Z-debug.log
-----> Build failed
       
       We're sorry this build is failing! You can troubleshoot common issues here:
       https://devcenter.heroku.com/articles/troubleshooting-node-deploys
       
       If you're stuck, please submit a ticket so we can help:
       https://help.heroku.com/
       
       Love,
       Heroku
       
 !     Push rejected, failed to compile Node.js app.
 !     Push failed
 
![image](https://user-images.githubusercontent.com/43907678/130787617-343968be-8d29-4407-9970-a457cfccbf49.png)

**Comment by quiet69** [comment]
build still failing :(
