### ISSUE TITLE
Here's a good news: Nitro snipers coded in Python aren't blocked by Heroku.

### ISSUE THREAD

**Issue by nichevulcan20** [GiorgioBrux/nitro-sniper-enhanced#119]
Can you make a new project (Nitro Sniper) that will be in Python? Don't delete the Nitro Sniper Enhanced project but yes Python Nitro snipers are really working on Heroku but the developers of those snipers are inactive to fix bugs. I request you to make one with the same features.

**Why am I sure that Python Snipers work?**
I tried to deploy the sniper. And it was deployed and was working!

**Comment by GiorgioBrux** [comment]
I will find a workaround for Heroku, I'm not gonna rewrite everything in python just for this reason. Maybe in the future.

**Comment by nichevulcan20** [comment]
> I will find a workaround for Heroku, I'm not gonna rewrite everything in python just for this reason. Maybe in the future.

oke bro
