### ISSUE TITLE
Heroku out of memory error

### ISSUE THREAD

**Issue by THEG77** [GiorgioBrux/nitro-sniper-enhanced#12]
Heroku throws error while logging into accounts when more than like 20-30 tokens used in an app.

**Comment by arnavpanigrahi** [comment]
thats a heroku limitation

**Comment by Cloudfry** [comment]
you need to pay

**Comment by GiorgioBrux** [comment]
As others have said, it's an heroku limitation. To go around that you can pay them, or host it yourself (either locally or by deploying the docker container)
