### ISSUE TITLE
[BUG] Heroku deployment

### ISSUE THREAD

**Issue by apexweeb** [GiorgioBrux/nitro-sniper-enhanced#121]
After the update i followed the instructions to deploy the sniper to heroku but it says "Your GitHub account (@apexweeb) does not have access to this repository, or it does not exist." on the heroku page

**Comment by GiorgioBrux** [comment]
Did you fork the repository? I can't see it, so it's either private or you didn't fork it.

**Comment by 3w7** [comment]
> Did you fork the repository? I can't see it, so it's either private or you didn't fork it.

u cant make a fork private, except if the owner of original repo changes it

**Comment by GiorgioBrux** [comment]
> > Did you fork the repository? I can't see it, so it's either private or you didn't fork it.
> 
> u cant make a fork private, except if the owner of original repo changes it

oh yeah you are right, I had completely forgotten. @apexweeb follow the instructions in the readme closely, you didn't make the fork.

**Comment by GiorgioBrux** [comment]
I'm closing this because of no answer. If you have the same issue open a new one.
