### ISSUE TITLE
Error on Replit

### ISSUE THREAD

**Issue by JohnnyBosak** [GiorgioBrux/nitro-sniper-enhanced#126]
Hi, I'm getting an error when launching the app on Replit 
![ScreenShotReplit](https://user-images.githubusercontent.com/74990227/127169712-b9a83243-ee45-4ae8-aee4-acff52e827f3.PNG)

**Comment by nichevulcan20** [comment]
try running the auto-format option because you might have deleted the `"", ''` mistakenly...

It's located at the top-right:

![image](https://user-images.githubusercontent.com/81959998/127193767-0a66ff21-f820-4b90-94af-3ceded71958b.png)

**Comment by JohnnyBosak** [comment]
Didn't resolve the issue. I also deleted the Replit App and created a new one, imported files from Github (used GiorgioBrux/nitro-sniper-enhanced) yet still getting the same error.

**Comment by JohnnyBosak** [comment]
I fixed the problem by adding node in .Replit command
