### ISSUE TITLE
Replit - Add secrets!

### ISSUE THREAD

**Issue by nichevulcan20** [GiorgioBrux/nitro-sniper-enhanced#127]
# Example

I did make a Discord Server Nuker in Python. My bot's token gets stolen every time, so I've decided to add some secret variables like this in the repl:

![image](https://user-images.githubusercontent.com/81959998/127191995-68757e7f-5cc7-4498-9ddb-7e847f4ee1dc.png)

Now, to import them I used to import os, and then did like this:
Instead of `token = value`
I added `token = VarName`
![image](https://user-images.githubusercontent.com/81959998/127192417-02c7eebc-ec1e-4e3b-a653-327ead892ce2.png)

And, the var values are already set in the repl, and its secure because if someone even forks the repl, he wont see the secrets.

![image](https://user-images.githubusercontent.com/81959998/127192743-139b1e21-deb3-4d43-bcf3-22a27e50af20.png)

# How about doing the same thing on your reply project!?

You can do add the thing like this on your replit project right? yes I know we need to make the vars manually in the secrets tab. But it will be so easy to use it if you add the variable-like thing in the replit project what u say!? No one can nuke our accounts, we will get 24/7 hosting on replit, and ye our token, guildTokens will be safe!

**Comment by GiorgioBrux** [comment]
I had no idea secrets existed, will look into it asap.

**Comment by nichevulcan20** [comment]
> I had no idea secrets existed, will look into it asap.
TY BROO! I was so worried due to your inactiveness

**Comment by nichevulcan20** [comment]
nitro sniper doesn't works on 2fa enabled account right?

**Comment by GiorgioBrux** [comment]
> nitro sniper doesn't works on 2fa enabled account right?

we are OT, but it does work.

**Comment by GiorgioBrux** [comment]
I'm gonna close this because of 1b499fae058815b856981a7b6f004eeee4c571e0. The .env file is hidden on replit to everyone else.

**Comment by nichevulcan20** [comment]
> I'm gonna close this because of [1b499fa](https://github.com/GiorgioBrux/nitro-sniper-enhanced/commit/1b499fae058815b856981a7b6f004eeee4c571e0). The .env file is hidden on replit to everyone else.

bro, my account got nuked within 10 mins after developing of deploying sniper on replit

**Comment by GiorgioBrux** [comment]
@nichevulcan20 open a new issue, that commit is probably unrelated

**Comment by nichevulcan20** [comment]
> @nichevulcan20 open a new issue, that commit is probably unrelated

okay
