### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by CheeseTheWeese** [GiorgioBrux/nitro-sniper-enhanced#128]
**I'm submitting a bug report**

**I'm running the lastest version**

**What is the expected behavior?**
Its supposed to automatically gift the sniped nitro it to my main account

**What is the current behavior?**
Its sniping real (i double checked) nitro dropped codes but it keeps saying my main token is invalid 
![image](https://user-images.githubusercontent.com/88008654/127197149-168df794-eff3-4cd2-8c64-fa1213b45438.png)

**Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix)
I'm using heroku and i did the same steps for getting the account token for my alt and my main, so im not sure why my main doesnt work.

**Comment by CheeseTheWeese** [comment]
It crashed for some reason and it now saying this 
![image](https://user-images.githubusercontent.com/88008654/127248716-ee52197d-7c1a-4084-b41e-f007d3e6f3de.png)

**Comment by CheeseTheWeese** [comment]
I re-did my main token and i woke up today to it saying 
![image](https://user-images.githubusercontent.com/88008654/127328390-f6cd2957-82ae-4b66-a945-7e383efc8af3.png)
but my main acc doesnt have the nitro,

**Comment by nichevulcan20** [comment]
By already-redeemed, this means the code is already claimed by someone

**Comment by CheeseTheWeese** [comment]
ah alr

**Comment by CheeseTheWeese** [comment]
i dont believe that there would be other snipers in there with a faster nitro sniper... this is kind of sketchy, i did an advanced searched for the gift and no one knew who got it. What if the owner is just taking the nitro that was sniped using his bots on our accs?
