### ISSUE TITLE
The heroku app keeps changing its state to crashed

### ISSUE THREAD

**Issue by brams1441** [GiorgioBrux/nitro-sniper-enhanced#13]
Always something like this 

> 2021-01-01T15:31:00.160896+00:00 heroku[worker.1]: Process exited with status 1
> 
> 2021-01-01T15:31:00.201958+00:00 heroku[worker.1]: State changed from up to crashed

But this here was my error that i encountered while posting this.

> 2021-01-01T15:30:45.094895+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_CHAR]: Invalid character in header content ["Authorization"]
> 
> 2021-01-01T15:30:45.094934+00:00 app[worker.1]:     at ClientRequest.setHeader (_http_outgoing.js:533:3)
> 
> 2021-01-01T15:30:45.094935+00:00 app[worker.1]:     at Snekfetch.set (/app/node_modules/snekfetch/src/index.js:75:20)
> 
> 2021-01-01T15:30:45.094936+00:00 app[worker.1]:     at APIRequest.gen (/app/node_modules/discord.js/src/client/rest/APIRequest.js:43:28)
> 
> 2021-01-01T15:30:45.094936+00:00 app[worker.1]:     at /app/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:59:20
> 
> 2021-01-01T15:30:45.094937+00:00 app[worker.1]:     at new Promise (<anonymous>)
> 
> 2021-01-01T15:30:45.094938+00:00 app[worker.1]:     at SequentialRequestHandler.execute (/app/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:58:12)
> 
> 2021-01-01T15:30:45.094938+00:00 app[worker.1]:     at SequentialRequestHandler.handle (/app/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:125:10)
> 
> 2021-01-01T15:30:45.094938+00:00 app[worker.1]:     at SequentialRequestHandler.push (/app/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:48:10)
> 
> 2021-01-01T15:30:45.094939+00:00 app[worker.1]:     at /app/node_modules/discord.js/src/client/rest/RESTManager.js:27:15
> 
> 2021-01-01T15:30:45.094939+00:00 app[worker.1]:     at new Promise (<anonymous>)
> 
> 2021-01-01T15:30:45.095455+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
> 
> 2021-01-01T15:30:45.095564+00:00 app[worker.1]: (node:4) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
> 
> 2021-01-01T15:31:00.106450+00:00 app[worker.1]: events.js:291
> 
> 2021-01-01T15:31:00.106467+00:00 app[worker.1]:       throw er; // Unhandled 'error' event
> 
> 2021-01-01T15:31:00.106468+00:00 app[worker.1]:       ^
> 
> 2021-01-01T15:31:00.106468+00:00 app[worker.1]: 
> 
> 2021-01-01T15:31:00.106485+00:00 app[worker.1]: Error: socket hang up
> 
> 2021-01-01T15:31:00.106510+00:00 app[worker.1]:     at connResetException (internal/errors.js:609:14)
> 
> 2021-01-01T15:31:00.106735+00:00 app[worker.1]:     at TLSSocket.socketOnEnd (_http_client.js:458:23)
> 
> 2021-01-01T15:31:00.106737+00:00 app[worker.1]:     at TLSSocket.emit (events.js:326:22)
> 
> 2021-01-01T15:31:00.106737+00:00 app[worker.1]:     at endReadableNT (_stream_readable.js:1241:12)
> 
> 2021-01-01T15:31:00.106739+00:00 app[worker.1]:     at processTicksAndRejections (internal/process/task_queues.js:84:21)
> 
> 2021-01-01T15:31:00.106740+00:00 app[worker.1]: Emitted 'error' event on ClientRequest instance at:
> 
> 2021-01-01T15:31:00.106740+00:00 app[worker.1]:     at TLSSocket.socketOnEnd (_http_client.js:458:9)
> 
> 2021-01-01T15:31:00.106741+00:00 app[worker.1]:     at TLSSocket.emit (events.js:326:22)
> 
> 2021-01-01T15:31:00.106741+00:00 app[worker.1]:     at endReadableNT (_stream_readable.js:1241:12)
> 
> 2021-01-01T15:31:00.106742+00:00 app[worker.1]:     at processTicksAndRejections (internal/process/task_queues.js:84:21) {
> 
> 2021-01-01T15:31:00.106743+00:00 app[worker.1]:   code: 'ECONNRESET'
> 
> 2021-01-01T15:31:00.106743+00:00 app[worker.1]: }
> 
> 2021-01-01T15:31:00.160896+00:00 heroku[worker.1]: Process exited with status 1
> 
> 2021-01-01T15:31:00.201958+00:00 heroku[worker.1]: State changed from up to crashed

**Comment by brams1441** [comment]
Seems to be working now so i think ill close this issue....

**Comment by GiorgioBrux** [comment]
It was probably a problem with heroku itself, I will add connection exceptions handling ASAP so it doesn't print that wall of text next time.
