### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by CheeseTheWeese** [GiorgioBrux/nitro-sniper-enhanced#132]
**I'm submitting a ...**
- [ ] bug report

**I'm running**
- [ ] the latest version

**What is the expected behavior?**
gives me the nitro

**What is the current behavior?**
says already redeemed. i thought this was a nitro sniper but why are all of the 20 codes I've gotten so far saying already redeemed? Does that mean there are other nitro snipers that are getting them?
![image](https://user-images.githubusercontent.com/88008654/127413079-3bdb3e7d-3540-460d-8aeb-0762af0f95b3.png)

**Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix)

**Comment by nichevulcan20** [comment]
by Already redeemed thing, this means that the nitro code is already claimed by someone. and there can be some conditions of getting this

- people drop already redeemed codes many times I have also seen that. 
- Other snipers can be fast to redeem the nitro like if ur having 200+ms then there are low chances to get nitro 

## Fix of the slow speed of the sniper
- join the servers which are of/near your region. 
- change the settings to false (obfuction, etc)
- if you have added alts and they're in too many servers then it's the cause of slow aniper.

**Comment by GiorgioBrux** [comment]
Basically what @nichevulcan20 said (thanks!).
The vast majority of the time it's the first thing (people dropping fake codes). If you don't have enough nitro add more alts.

**Comment by CheeseTheWeese** [comment]
alr ty!
