### ISSUE TITLE
[BUG] localmachine installing

### ISSUE THREAD

**Issue by Radjejszyn** [GiorgioBrux/nitro-sniper-enhanced#143]
**I'm submitting a ...**
- [ ] bug report

**I'm running**
- [ ] the latest version

**What is the expected behavior?**
Installing and running on local machine

**What is the current behavior?**
not installing at *npm install* step ( local machine)

whole log-file

npm ERR! command C:\Windows\system32\cmd.exe /d /s /c node-gyp rebuild
npm ERR! Building the projects in this solution one at a time. To enable parallel build, please add the "-m" switch.
npm ERR!   adler32.c
npm ERR!   compress.c
npm ERR!   crc32.c
npm ERR!   deflate.c
npm ERR!   gzclose.c
npm ERR!   gzlib.c
npm ERR!   gzread.c
npm ERR!   gzwrite.c
npm ERR!   infback.c
npm ERR!   inffast.c
npm ERR!   inflate.c
npm ERR!   inftrees.c
npm ERR!   trees.c
npm ERR!   uncompr.c
npm ERR!   zutil.c
npm ERR!   win_delay_load_hook.cc
npm ERR!   zlib.vcxproj -> C:\Users\llpou\nitro-sniper\node_modules\erlpack\build\Release\\zlib.lib
npm ERR!   erlpack.cc
npm ERR! C:\Users\llpou\AppData\Local\node-gyp\Cache\16.8.0\include\node\node.h(63,10): fatal error C1083: Cannot open include file: 'v8.h': No such file or directory [C:\Users\llpou\nitro-sniper\node_modules\erlpack\build\erlpack.vcxproj]
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@7.1.2
npm ERR! gyp info using node@16.8.0 | win32 | x64
npm ERR! gyp info find Python using Python version 3.9.6 found at "C:\Users\llpou\AppData\Local\Programs\Python\Python39\python.exe"
npm ERR! gyp info find VS using VS2019 (16.11.31624.102) found at:
npm ERR! gyp info find VS "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community"
npm ERR! gyp info find VS run with --verbose for detailed information
npm ERR! (node:21616) [DEP0150] DeprecationWarning: Setting process.config is deprecated. In the future the property will be read-only.
npm ERR! (Use `node --trace-deprecation ...` to show where the warning was created)
npm ERR! gyp info spawn C:\Users\llpou\AppData\Local\Programs\Python\Python39\python.exe
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   'C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'msvs',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   'C:\\Users\\llpou\\nitro-sniper\\node_modules\\erlpack\\build\\config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   'C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   'C:\\Users\\llpou\\AppData\\Local\\node-gyp\\Cache\\16.8.0\\include\\node\\common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=C:\\Users\\llpou\\AppData\\Local\\node-gyp\\Cache\\16.8.0',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=C:\\\\Users\\\\llpou\\\\AppData\\\\Local\\\\node-gyp\\\\Cache\\\\16.8.0\\\\<(target_arch)\\\\node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=C:\\Users\\llpou\\nitro-sniper\\node_modules\\erlpack',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'C:\\Users\\llpou\\nitro-sniper\\node_modules\\erlpack\\build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp info spawn C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\MSBuild.exe
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   'build/binding.sln',
npm ERR! gyp info spawn args   '/clp:Verbosity=minimal',
npm ERR! gyp info spawn args   '/nologo',
npm ERR! gyp info spawn args   '/p:Configuration=Release;Platform=x64'
npm ERR! gyp info spawn args ]
npm ERR! gyp ERR! build error
npm ERR! gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\MSBuild.exe` failed with exit code: 1
npm ERR! gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:194:23)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:394:28)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
npm ERR! gyp ERR! System Windows_NT 10.0.19043
npm ERR! gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
npm ERR! gyp ERR! cwd C:\Users\llpou\nitro-sniper\node_modules\erlpack
npm ERR! gyp ERR! node -v v16.8.0
npm ERR! gyp ERR! node-gyp -v v7.1.2
npm ERR! gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\llpou\AppData\Local\npm-cache\_logs\2021-08-30T19_58_38_929Z-debug.log

**Comment by GiorgioBrux** [comment]
Looks like a problem with elrpack. You can safely remove it from the dependencies and run npm-install again, or try with WSL.

**Comment by GiorgioBrux** [comment]
Closing this. If anyone has the same issue, do the above.
