### ISSUE TITLE
[REQ] -- Solution of #135 issue

### ISSUE THREAD

**Issue by ItzMeeGaurav** [GiorgioBrux/nitro-sniper-enhanced#145]
# Edit : Im facing an error, please review this idea and correct if when possible

**Is your feature request related to a problem? Please describe.**
The solution is of the issue #135 
I know that there are so many people who keeps forking other people's projects in the search of private info, such as tokens and passwords. Because your nitro sniper needs to enter the token in the file's **code**, people are able to see the token. Because replit has a different way to store secret variables. And this thing was discussed in the issue 135, but I have the solution of it. 

**Describe the solution you'd like**
As he gave the example of storing secrets in Python, node is also easy to be used to store secrets.
I'm posting some screenshots for better understanding.

Unfortunately,
I cant find the `.env` file there because replit deletes it. So i created a file named `dotenv` myself 
![image](https://user-images.githubusercontent.com/89828453/131448572-671192c5-e7e1-4ef2-a020-0c0b03757541.png)

And I pasted this thing, by copting it from `.env` directly without forking your project:

![image](https://user-images.githubusercontent.com/89828453/131448674-eb0d5968-cb0d-4c83-8e9f-fb59d65198c8.png)

Now, on the top of the line, I inserted the secrets

![image](https://user-images.githubusercontent.com/89828453/131448892-eae3935d-284c-4453-bdfd-9d25e6174f44.png)

Also added these in the fields instead of token

![image](https://user-images.githubusercontent.com/89828453/131448972-18b6e504-c829-49cd-8807-5932490409a2.png)

# Things we have to do manually:
Once this is done, we have to create the secrets manually and to put the values in it, I mean, the secrets in the code have been done and we dont need to mess up with it, we just have to add two secrets like mainToken and guildTokens
Just like the example below and to save it

![image](https://user-images.githubusercontent.com/89828453/131449203-3217e7fd-5efd-42da-8fc9-a643ec8cd9f5.png)

After making changes it will look like it:

![image](https://user-images.githubusercontent.com/89828453/131449278-4a8241cf-e0fc-4b24-a001-7d01e6a82bbe.png)

That's it! 
# messed up suggestion? you can close it if you don't like it

**Comment by GiorgioBrux** [comment]
I know about secrets, will implement them asap. Sorry for the delay.

**Comment by nichevulcan20** [comment]
> I know about secrets, will implement them asap. Sorry for the delay.

nice bro
