### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by quiet69** [GiorgioBrux/nitro-sniper-enhanced#148]
i think the status indicators are not working, my main always shows up as invisible.... think its a bug (have it set to dnd)

**Comment by GiorgioBrux** [comment]
The sniper doesn't set the status of the main token on purpose atm.

**Comment by quiet69** [comment]
aah ok... thanks for clarifying :)

**Comment by GiorgioBrux** [comment]
Closing this then
