### ISSUE TITLE
[BUG] no message notification on discord 

### ISSUE THREAD

**Issue by Radjejszyn** [GiorgioBrux/nitro-sniper-enhanced#149]
**I'm submitting a ...**
- [x] bug report

**I'm running**
- [x] the latest version

**What is the expected behavior?**
To get notification .

**What is the current behavior?**
After setting up discord sniper on heroku, i dont get any notification from discord on my mobile. 
I tried to change the main account status but nothing has helped 

After putting the sniper offline, notification works normally.

**Comment by quiet69** [comment]
close this bug lol. discord thinks you're already logged in to the web and so you wont receive any notifications

**Comment by Radjejszyn** [comment]
> close this edit lol. discord thinks you're already logged in to the web and so you wont receive any notifications

Yeah but the problem is, on a different sniper It was working normally. I got notifications etc

**Comment by GiorgioBrux** [comment]
Did you try setting `usemain` to `false`?

**Comment by Radjejszyn** [comment]
> Did you try setting `usemain` to `false`?

I mean yeah, it works but I wanted to use my main account too.
But I will just make new alt and join every server that I'm on main.
