### ISSUE TITLE
[BUG] Error: Cannot find module 'dotenv'

### ISSUE THREAD

**Issue by depthso** [GiorgioBrux/nitro-sniper-enhanced#152]
![image](https://user-images.githubusercontent.com/86912923/134194873-37f774f0-d8ae-4823-b437-6f5226099d4f.png)

**Comment by GiorgioBrux** [comment]
Did you `npm install`?

**Comment by Whoogivesashit** [comment]
> Did you `npm install`?

![image](https://user-images.githubusercontent.com/86912923/134538042-21ee6a99-a00f-4e3b-bb89-31779f88b379.png)

**Comment by GiorgioBrux** [comment]
🤦 You didn't cd into the sniper folder, you are in system32.
