### ISSUE TITLE
Donation  / Enhancement

### ISSUE THREAD

**Issue by bonxz** [GiorgioBrux/nitro-sniper-enhanced#18]
If you make a donation page I would also like to donate something for your work. Or a https://www.buymeacoffee.com/ 

Among other things it would be cool if you could set the status of the accounts. I mean "online, offline, idle, dnd, invisible".

And maybe you could add more pages that are similar to Privnote. (pastebin.com, safenote.co, temp.pm, hastebin.com)

And it would be better if you maybe start the discussion round in Github for the repository.

**Comment by GiorgioBrux** [comment]
I'll think about donations, but I would very much appreciate PRs if you can code!

Those are all good ideas, but please create a separate issue for each so I can better keep track of them, thanks!
