### ISSUE TITLE
Add embed support

### ISSUE THREAD

**Issue by iiLeafy** [GiorgioBrux/nitro-sniper-enhanced#19]
I'm not sure if this already exists or not but does it check for links in a embed, if it doesn't this can be a suggestion.

**Comment by GiorgioBrux** [comment]
It should check already, let me know if you find any case where it doesn't :)

**Comment by 7fe2752182d43f856b49a802e36d597c78ae87b** [comment]
Doesn't appear to get any of these links in an embed 
![image](https://user-images.githubusercontent.com/69968736/104131612-3357f180-532c-11eb-808e-c94a90f1ca65.png)
