### ISSUE TITLE
'Payment source required to redeem gift'

### ISSUE THREAD

**Issue by GiorgioBrux** [GiorgioBrux/nitro-sniper-enhanced#23]
'Payment source required to redeem gift' when redeeming some type of gifts.

**Comment by 7fe2752182d43f856b49a802e36d597c78ae87b** [comment]
The Discord web/app client sends `{channel_id: null, payment_source_id: null}` in the request payload when redeeming. Unsure if this prevents the bug but seems related.
Some other snipers fill in the channel_id and payment_source automatically, possibly to make the request look more 'real'.

**Comment by GiorgioBrux** [comment]
Interesting, going to bed but will see tomorrow if they make a difference.

Anyway, if the discord web/app fills them, we should fill them too regardless to make it look more realistic.
