### ISSUE TITLE
Appreciation

### ISSUE THREAD

**Issue by iiLeafy** [GiorgioBrux/nitro-sniper-enhanced#28]
This isnt a issue, but really just appreciation on how much dedication you put into this, everyday you do multiple commits either bug fixes, or updates and also many features which other snipers dont have, but also I have a feature which ill suggest is support for invalid, fake and already redeemed webhook messages either on the same webhook option or add more options in the dotenv.

Thank you for this sniper.
~Leafy

**Comment by GiorgioBrux** [comment]
I'm truly happy my work is appreciated, thanks <3

I plan to eventually add everything that seems proper.
If you have any good idea that isn't an issue already, feel free to open an issue (remember, one separate issue each!).

Will close this, but thanks for taking the time to write a message out!
