### ISSUE TITLE
Add webhooks for failed code redeems

### ISSUE THREAD

**Issue by ManualMap** [GiorgioBrux/nitro-sniper-enhanced#29]
I didnt know how to title it properly, but could you add something like more options in dotenv like

webhookFake:"webhook for fake"
and same for invalid and already redeemed

and it can be optional

**Comment by GiorgioBrux** [comment]
I can do that, but is it really useful?

Will keep this as a low-priority thing.

**Comment by iiLeafy** [comment]
> I can do that, but is it really useful?
> 
> Will keep this as a low-priority thing.

idk for others but ignits useful for me to see stuff without going to like heroku and stuff
