### ISSUE TITLE
XBOX Games Codes?

### ISSUE THREAD

**Issue by bonxz** [GiorgioBrux/nitro-sniper-enhanced#31]
Recently, I have often now already received the message that I need a payment method. Have also seen other Sniper programs that have a workaround.

Xbox codes can apparently not be redeemed on all accounts

`2021-01-12T18:40:45.844129+00:00 app[worker.1]: [Nitro Sniper] (ERROR) Tried to redeem code [3ytqzG7kAQYw6kM2xHpbPSat] but got error: Payment source required to redeem gift..`

The codes also seem to be longer

**Comment by GiorgioBrux** [comment]
That explains it.

If possible, can you share the workaround you've seen, so I can implement it here too?
That code is 24 characters, if you have seen something longer tell me and I will change the value in the sniper.

Thanks

**Comment by bonxz** [comment]
> 
> 
> That explains it.
> 
> If possible, can you share the workaround you've seen, so I can implement it here too?
> That code is 24 characters, if you have seen something longer tell me and I will change the value in the sniper.
> 
> Thanks

[](https://github.com/noto-rious/Nitro.Self-V3/issues/8)

Maybe this link can help you out.
