### ISSUE TITLE
Main Token Status too

### ISSUE THREAD

**Issue by bonxz** [GiorgioBrux/nitro-sniper-enhanced#33]
Thanks for adding the function already. But I still have one optimization. You have made it now only for the Alt Tokens. Could you also add it for the Main Token?

_Originally posted by @bonxz in https://github.com/GiorgioBrux/nitro-sniper-enhanced/issues/21#issuecomment-758693644_

**Comment by brams1441** [comment]
Yeah i think it would be nice to have an option like that

**Comment by slow** [comment]
This is not possible unless the sniper is logged in on the main account, as `useMain` is an option this could be added but if its off it would be a very useless variable.

This would just cause cluttered env variables on heroku, i haven't looked at the code for the status but i am guessing that it uses the same status that you specified for your alts.
