### ISSUE TITLE
[1.5.1] No Payment source 

### ISSUE THREAD

**Issue by bonxz** [GiorgioBrux/nitro-sniper-enhanced#35]
The new version doesn't seem to work quite right after all. I have not entered a payment method on my Main Token and as soon as I start the bot, it crashes immediately.

```
2021-01-13T23:14:29.099460+00:00 app[worker.1]: [Nitro Sniper] (FATAL ERROR) Main token does not have a billing source.
2021-01-13T23:14:29.099712+00:00 app[worker.1]: [Nitro Sniper] (FATAL ERROR) Quitting...
2021-01-13T23:14:29.147010+00:00 heroku[worker.1]: Process exited with status 0
2021-01-13T23:14:29.173724+00:00 heroku[worker.1]: State changed from up to crashed
```

before, i could use the bot without a payment method.

**Comment by bonxz** [comment]
> The new version doesn't seem to work quite right after all. I have not entered a payment method on my Main Token and as soon as I start the bot, it crashes immediately.
> 
> ```
> 2021-01-13T23:14:29.099460+00:00 app[worker.1]: [Nitro Sniper] (FATAL ERROR) Main token does not have a billing source.
> 2021-01-13T23:14:29.099712+00:00 app[worker.1]: [Nitro Sniper] (FATAL ERROR) Quitting...
> 2021-01-13T23:14:29.147010+00:00 heroku[worker.1]: Process exited with status 0
> 2021-01-13T23:14:29.173724+00:00 heroku[worker.1]: State changed from up to crashed
> ```


before, i could use the bot without a payment method.

**Comment by GiorgioBrux** [comment]
You are right, will make it so it's possible to use the sniper without the billing source in the next update,
