### ISSUE TITLE
Sync Github's repository to Heroku...

### ISSUE THREAD

**Issue by sonicm35** [GiorgioBrux/nitro-sniper-enhanced#38]
Hey,
Please, help ...

**Issue:**
How i sync Github's repository to Heroku...
I mean whenever the code change to Github's repo... than how automatically it can also be change on heroku app...? & i don't need to create new Heroku app again & again.
it would be highly appreciate to solve this issue.

I hope you'll understand,
Ty.

**Comment by bonxz** [comment]
https://github.com/GiorgioBrux/nitro-sniper-enhanced/issues/7#issuecomment-692116471

**Comment by bonxz** [comment]
If you want it to be automatic, you can also copy the repository and use the Github pull bot (https://github.com/apps/pull) to automatically update it whenever a new Update.
You can then add your own repository to Heroku and an update will be made there automatically and the bot will also be started again.

**Comment by GiorgioBrux** [comment]
Basically what @bonxz said. I thought about adding some code for auto-updates but ultimately decided against it.
Will maybe add instructions to setup the fork+the pull bot in the readme, but it isn't difficult.

If you have any problem feel free to open another issue!
