### ISSUE TITLE
[Suggestion] repl.it support

### ISSUE THREAD

**Issue by sonicm35** [GiorgioBrux/nitro-sniper-enhanced#42]
Hey..
Can you add support for __**https://repl.it/**__ as like heroku...
i mean, want to host that code on repl.it...
How can i do that?
or add some details in README.

**Comment by GiorgioBrux** [comment]
Look up some guides online, I have never used that.
Will add when I finish with other issues.

**Comment by DarkGD123** [comment]
Isnt repl.it repos are public?

**Comment by brams1441** [comment]
> 
> 
> Isnt repl.it repos are public?

You can pay $5 for private repos

**Comment by DarkGD123** [comment]
> > Isnt repl.it repos are public?
> 
> You can pay $5 for private repos

Hmm... Seems interesting

**Comment by iiLeafy** [comment]
> > > Isnt repl.it repos are public?
> > 
> > You can pay $5 for private repos
> 
> Hmm... Seems interesting

the code is public, but u can use a dotenv file which will be hidden, but i think it has to be .env not dotenv, not really sure

**Comment by DarkGD123** [comment]
https://docs.repl.it/repls/secret-keys

**Comment by GiorgioBrux** [comment]
The problem I think with repl.it is that (at least when I tried it) they used an old node version which isn't supported by discord.js v12. I will look into it again asap tho.
