### ISSUE TITLE
Only snipe classic or nitro codes

### ISSUE THREAD

**Issue by sonicm35** [GiorgioBrux/nitro-sniper-enhanced#43]
An option to Snipe only Classic codes "when activated" via nitro-code length;
& 
Option to Snipe only Nitro boost code "when activated" via nitro-code length.

**Comment by iiLeafy** [comment]
Why though, it seems really useless.

**Comment by GiorgioBrux** [comment]
I don't think nitro classic and normal have different code lengths, but maybe I misunderstood what you want. Can you explain it more clearly?

**Comment by slow** [comment]
This is possible but with a very big sacrifice. Nitro codes cannot be distinguished without fetching the code info which by then, you already lose the nitro to another sniper.
