### ISSUE TITLE
help...

### ISSUE THREAD

**Issue by sonicm35** [GiorgioBrux/nitro-sniper-enhanced#44]
**Need v3.1.0 badly...**
![image](https://user-images.githubusercontent.com/38960451/105405235-be9a8680-5c4c-11eb-926a-417faf6f6494.png)

**Comment by brams1441** [comment]
I'm confused, what do you need help with?

**Comment by sonicm35** [comment]
> 3.1.0 is actually an old version because when I switched to semantic-release I started from 1.0.0 again. Sorry for the confusion.

Can you please share that code? or link ...
