### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by sonicm35** [GiorgioBrux/nitro-sniper-enhanced#47]
![image](https://user-images.githubusercontent.com/38960451/105740780-57861600-5f5b-11eb-8a0f-344ae10a7850.png)
![image](https://i.imgur.com/tKt47E5.png)
![image](https://i.imgur.com/Y5osUgZ.png)
https://github.com/GiorgioBrux/nitro-sniper-enhanced/issues/41#issuecomment-766625243

**Comment by GiorgioBrux** [comment]
Fixed the heroku problem with f36b445eabd3959352f6ced8c116b115cb9e4f18 and 330b0a1a7fbae69a19b8865d95594913fa8fc848. Regarding the first two screens, what node version are you on?

**Comment by SammCheese** [comment]
v12.16.3

**Comment by GiorgioBrux** [comment]
> v12.16.3

@SammCheese that's probably the problem. Try with nodejs 14.x

**Comment by GiorgioBrux** [comment]
Closing this because it's stale. If someone has a similar problem, open another issue please.
