### ISSUE TITLE
not sniping anymore

### ISSUE THREAD

**Issue by formulayyy** [GiorgioBrux/nitro-sniper-enhanced#48]
hello i've noticed that the sniper isn't sniping any codes anymore. it just shows the codes that are being sniped none of them get redeemed. i used to get 1-2 nitros everyday but now it's zero, it's been like that for more than a week now. i have the old version. i switched to the new one on another account just to test but no luck sadly. any help wil be greatly appreciated.

**Comment by brams1441** [comment]
Sniping is just based on luck tbh, last time i claimed nitro was 8 days ago. What you can do is join more servers or add some alts

**Comment by GiorgioBrux** [comment]
I doubt the problem is the sniper but as brams said it's probably just bad luck. If you know for sure there is a problem in the redeeming process open another issue.
