### ISSUE TITLE
webhook for redeemed nitro

### ISSUE THREAD

**Issue by IzukuMidoriyaPHP** [GiorgioBrux/nitro-sniper-enhanced#49]
webhook for already redeemed nitros?

**Comment by IzukuMidoriyaPHP** [comment]
like failed to redeem nitros i mean

**Comment by brams1441** [comment]
I don think that will be useful, why would you need to know the codes that didnt work?

**Comment by GiorgioBrux** [comment]
Unless I misunderstood, this is a duplicate of #29 so I'm closing.
