### ISSUE TITLE
Will this nitro sniper be discontinued?

### ISSUE THREAD

**Issue by ibndiaye** [GiorgioBrux/nitro-sniper-enhanced#50]
I tried hosting it on heroku and i get this error.
![image](https://user-images.githubusercontent.com/63436162/107927771-bf86b580-6f77-11eb-8679-c4b69a810782.png)

And i recently saw that you forked another sniper

Im just curious

**Comment by GiorgioBrux** [comment]
Hi, I don't plan on discontinuing this sniper for now. Eventually, I will probably migrate to the new slow's base, but I will still use this repo. Will deal with the heroku issue on #51.
