### ISSUE TITLE
Heroku link not working

### ISSUE THREAD

**Issue by stressatoo-lang** [GiorgioBrux/nitro-sniper-enhanced#51]
**Heroku button isn't working**, so I created a new one by editing nitro-sniper to nitro-sniper-enhanced

New one is:
https://dashboard.heroku.com/new?button-url=https%3A%2F%2Fgithub.com%2Fgiorgiobrux%2Fnitro-sniper-enhanced&template=https%3A%2F%2Fgithub.com%2Fgiorgiobrux%2Fnitro-sniper-enhanced%2Ftree%2Fmaster

P.S.: I'm also Italian, big fan.

**Comment by GiorgioBrux** [comment]
Thanks, I didn't notice.

I'm happy that other Italians use my sniper <3
