### ISSUE TITLE
When deploying on heroku you encounter an error

### ISSUE THREAD

**Issue by ibndiaye** [GiorgioBrux/nitro-sniper-enhanced#53]
Hello I tried deploying the sniper and when I do I get this error.

![image](https://user-images.githubusercontent.com/63436162/108610653-acd90a00-73d7-11eb-8012-f68fcb4d5e75.png)

Do you know how to fix this?

**Comment by DarkGD123** [comment]
i had that problem as well

**Comment by GiorgioBrux** [comment]
Hi, could you confirm if there is the same issue with b9e51bca2c6f181975a2c88906edbaebc86bb546?

**Comment by DarkGD123** [comment]
It works normally now, how about you @ibndiaye is it working?

**Comment by ibndiaye** [comment]
@DarkGD123 I'll give it another try

**Comment by ibndiaye** [comment]
@GiorgioBrux I just deployed and no issues, thanks for fixing the issue so quickly!

**Comment by GiorgioBrux** [comment]
> @GiorgioBrux I just deployed and no issues, thanks for fixing the issue so quickly!

Thank you for opening an issue, have a nice Sunday everyone.
