### ISSUE TITLE
Files

### ISSUE THREAD

**Issue by Atranip** [GiorgioBrux/nitro-sniper-enhanced#58]
After sniping a privnote it says Saved to file ./notes/privnote-XXXXXXXX.txt where can i access it?

**Comment by DarkGD123** [comment]
i think you cant access it unless you do something like on heroku git, or on repl.it you can see it and view it..

i dont really know how to access nor read my files in heroku cuz i mostly use repl.it but heroku is good

**Comment by Atranip** [comment]
> i think you cant access it unless you do something like on heroku git, or on repl.it you can see it and view it..
> 
> i dont really know how to access nor read my files in heroku cuz i mostly use repl.it but heroku is good

oh
