### ISSUE TITLE
 Token LOGGERS Join that server in which WEBHOOKS are, THEY tried to hack my account, 

### ISSUE THREAD

**Issue by NicheVulcan** [GiorgioBrux/nitro-sniper-enhanced#61]
HEY 
I set a webhook while deploying the app on Heroku, but when a code sniped, a webhook sent a message BUT someone else also joined the server from nowhere IDK from where but he was giving tip to never share token to anyone BUT he gained trust. He made a profile picture for me. He gave me a link to download the pic but MY IP, My phone number, my account token LOGGED and HE misused my account, my account was mass DM-ing people, and even leaving servers and removing friends from the list. Have you made this sniper so that you teach a lesson to people who really want Discord Nitro? The persons who trusted the sniper got Nitro, this is really fantastic but WHY these hackers come and ruin the life? I think some people hijacked your sniper XD (on Heroku, I turned on the option to get pinged when nitro snipes. When it sniped after a few hours of deploying, an unknown person came and pinged me that he is a developer from replit and gave the tip which was discussed earlier. On the next day, he almost hacked me, and I just changed the password and blocked him, I even deleted the app on Heroku.

PLEASE make your sniper safe so that I can deploy your sniper again. I was disappointed to know that you're not a good person or a bad person who hijacked the sniper. I'm not reporting this because I could lose Nitro, I reported this because I could lose all of my friends because of you. I beg you please clean all the clutter going on at your sniper. 

Regards,
NicheVulcan.

**Comment by NicheVulcan** [comment]
also, the app keeps crashing on Heroku, I saw the error on LOGS

**Comment by DarkGD123** [comment]
Probably you just leaked your server invite

**Comment by NicheVulcan** [comment]
> Probably you just leaked your server invite

NO BRO I never even created any invite link of that server

**Comment by GiorgioBrux** [comment]
Someone got your token by other means, make sure your pc is clean. The sniper is not hijacked or anything.

**Comment by stop-bark** [comment]
Is it also possible that repl.it just didn't hide the token?

**Comment by nichevulcan20** [comment]
> Is it also possible that repl.it just didn't hide the token?

bro never deploy the sniper on replit unless u have premium and ability to make repls private i got nuked under an hour after deploying on replit

**Comment by Laar-u** [comment]
> 
> 
> > Is it also possible that repl.it just didn't hide the token?
> 
> bro never deploy the sniper on replit unless u have premium and ability to make repls private i got nuked under an hour after deploying on replit

if it is a .env then it will be hidden, eitherway i have my own rdp so i dont need repl.it
