### ISSUE TITLE
App keeps crashing on Heroku

### ISSUE THREAD

**Issue by NicheVulcan** [GiorgioBrux/nitro-sniper-enhanced#62]
Hi,
the sniper gives errors on Heroku logs whenever I close my Discord tab. It says the app crashed with status 401 or something. I can not give a screenshot because I deleted the app because of token loggers going around nowadays and my account got hacked by them, I told you about that issue earlier.

**Comment by GiorgioBrux** [comment]
Will keep this open for a while, if someone has the same issue please post logs.

**Comment by NicheVulcan** [comment]
> Will keep this open for a while, if someone has the same issue please post logs.

but bro what about the token loggers who interfare between the sniping process? my account is in danger please do actions on those hackers

**Comment by GiorgioBrux** [comment]
@NicheVulcan 

1. This isn't the right issue.
2. The sniper is completely safe (it's even opensource, you can check for yourself), so either someone hacked your heroku account or got your token by other means.

**Comment by NicheVulcan** [comment]
> @NicheVulcan
> 
> 1. This isn't the right issue.
> 2. The sniper is completely safe (it's even opensource, you can check for yourself), so either someone hacked your heroku account or got your token by other means.

thanks for making me realize that the sniper is safe. but the incident that happened to me some days ago was horrible. someone named itSguYs joined my server in which the webhook was enabled. I didn't even create any invite link of that webhook server but when the code has sniped, someone joined that server and told me that he is a developer from replit and all. I had enabled an option on Heroku that if the nitro has sniped so i will get a ping. is that is the cause of it? or maybe it could be another person hacking around. because he also has a linked yt channel in which he uploaded a video and there he nuked a server that had 25k members.

I trust you bro that you're true. I'm going to deploy the app again on Heroku. 
Thank you so much for the sniper! Love you, my brother!

**Comment by GiorgioBrux** [comment]
@NicheVulcan 

1. Again, this is not the right issue.
2. If you didn't create any invite, no one had invite perms other than you and someone joined your server, then your token was leaked. Check that you don't have any token stealer on your pc and that all places where your token may be stored are safe (heroku, etc.).
