### ISSUE TITLE
Auto-fetching user agent on heroku

### ISSUE THREAD

**Issue by ManualMap** [GiorgioBrux/nitro-sniper-enhanced#63]
So if you host it on heroku, and whenever it attempts to get the user agent on there it just returns
`[Nitro Sniper] (ERROR) There was an error fetching the latest chrome user agent: Error: Request failed with status code 403. Using default...`
If you host it locally no problem, on repl.it I'm not sure.

**Comment by DarkGD123** [comment]
It works sometimes on repl.it
