### ISSUE TITLE
Many friends say that im ignoring them due to 24/7 DND mode

### ISSUE THREAD

**Issue by ItzMeAakash** [GiorgioBrux/nitro-sniper-enhanced#67]
hey, due to the sniper im always on DND and i have some problems and my friends feel like im ignoring them... is there any way to make me invisible when im not using Discord? the option where guildtokenstatus i put to "invisible" it dosent works because i use through main token.. 

can i do one thing? 

- set UseMain to False
- set my alt's token in Main Token and that acct dosent join any server
- use my main account's token in guild tokens
- and now set it to invisible option from guild token status option

will it claim nitro gifts only to my main account token which is in GuildTokens section because i have turned useMain off?

**Comment by GiorgioBrux** [comment]
If you set `useMain` to false, it won't be used for sniping but codes will still be redeemed there.

At the moment, the tokenStatus applies only to guild tokens. For the main token, there is already a feature request open (#33). 

The DND thing is weird though. Try to stop the sniper, go online manually (so remove dnd), wait ~10 minutes and start the sniper again. Then quit your discord client and see your status. Is it still dnd?

**Comment by ItzMeAakash** [comment]
yes it's still DND. but i have an experiment, that, if i made these changes:

MainToken - my alt 
i will put my alt token to main token, and that account will not join any server so it is impossible to get nitro to it

GuildToken - My token
now, my main account will be set to guild toke

guildTokenStatus - invisible
so i had put my main token in guild token so obviously i will be offline whenever im not using Discord.

Result - 
My alt --> which is in main but not able to snipe cuz it is in no server

my main --> will snipe and can be invisible 

is it correct experiment?
useMain - False
this will also now redeem nitro from guild tokens right?

**Comment by stop-bark** [comment]
but it claims from guildtoken onto maintoken, so it will claim on ur alt

**Comment by ItzMeAakash** [comment]
> but it claims from guildtoken onto maintoken, so it will claim on ur alt

but what if i set UseMain to false

**Comment by ItzMeAakash** [comment]
@GiorgioBrux i request you to please add status for MainToken too. ☺️

**Comment by stop-bark** [comment]
> > but it claims from guildtoken onto maintoken, so it will claim on ur alt
> 
> but what if i set UseMain to false

that just disables using main to snipe, it will still claim from alt to main

**Comment by DarkGD123** [comment]
Just set it to invisible or offline

**Comment by GiorgioBrux** [comment]
Again, there is already a feature request for MainToken status (#33).
I will work on this asap. If you want to continue this discussion do so on #33 as it's directly related.
