### ISSUE TITLE
getting this error for some days now

### ISSUE THREAD

**Issue by formulayyy** [GiorgioBrux/nitro-sniper-enhanced#68]
![image](https://user-images.githubusercontent.com/71617943/113266148-57edb500-92ee-11eb-8192-b8104a3d6d40.png)

ive been getting this error whenever i try to start the sniper

**Comment by DarkGD123** [comment]
I never gotten this error.. Hmmm

**Comment by formulayyy** [comment]
> I never gotten this error.. Hmmm

i never used to get it either, it has started just now, apparently its been a week and idk what's causing it. ive tried resetting tokens and it still hasnt changed anything

**Comment by stop-bark** [comment]
have you tried updating to the latest version

**Comment by formulayyy** [comment]
> have you tried updating to the latest version

it is updated to the latest version

**Comment by GiorgioBrux** [comment]
Are you on node 14?

**Comment by formulayyy** [comment]
yes it's working on a new one, i just checked but the new one is slower than the older version which ive been using for a while. is there any fix for it or would i have to use the new one?

**Comment by GiorgioBrux** [comment]
@formulayyy I really doubt it's slower because of the code, what version were you running?

**Comment by formulayyy** [comment]
![IMG_20210401_192338.jpg](https://user-images.githubusercontent.com/71617943/113308612-c7c86380-931f-11eb-81ca-4ff31a265970.jpg)

this one, probably the oldest one I believe

**Comment by GiorgioBrux** [comment]
Yeah that's very old, something like 3 months.
The main part of the code hasn't changed much, you can achieve the same speed as before by turning all the features off if you wish.

Closing this as you solved the original issue.
