### ISSUE TITLE
I'm DND Even after setting mainStatus to invisible

### ISSUE THREAD

**Issue by ItzMeAakash** [GiorgioBrux/nitro-sniper-enhanced#78]
I deployed the sniper oh Heroku some hours ago... I was invisible whenever i was not using Discord i've checked from my alt from another device. but after some hours when i was not using Discord i was in DND Mode with my status, even after clearing app from recent lists. I've checked the app isn't running on any other device with my account. Please fix it.

**Comment by ItzMeAakash** [comment]
One more thing, my account went to invisible thank god. but it happens after some minutes after not using Discord. in other words, 

If i stop using Discord then I'm DND for some minutes

just after some minutes i turn to Invisible. 

can't it be instant output? it was working instantly when i was not using discord some hours ago, but the problem is happening now.

**Comment by GiorgioBrux** [comment]
It might be possible, I will look into it. No guarantees though.

**Comment by ItzMeAakash** [comment]
> It might be possible, I will look into it. No guarantees though.

ok

**Comment by nichevulcan20** [comment]
hey bro no need to fix this because this happens to my friends too that if they close discord then they're online/dnd/idle for some time. i also tried this to my alt which was sniper-free. however, my friends are also the only ones who can access their accounts.

**Comment by GiorgioBrux** [comment]
Thanks @nichevulcan20, good to know. Will close this then.
