### ISSUE TITLE
App keeps crashing on heroku

### ISSUE THREAD

**Issue by nichevulcan20** [GiorgioBrux/nitro-sniper-enhanced#81]
![image](https://user-images.githubusercontent.com/81959998/114294724-2333e780-9abe-11eb-8d0a-f99f9c738201.png)

as u can see this keeps crashing

**Comment by GiorgioBrux** [comment]
Can you try to recreate the app and see if it still happens?

**Comment by nichevulcan20** [comment]
> Can you try to recreate the app and see if it still happens?

sure bro just some minutes...

**Comment by GiorgioBrux** [comment]
Guess this is solved so I'm gonna close it.
