### ISSUE TITLE
bear with me

### ISSUE THREAD

**Issue by arnavpanigrahi** [GiorgioBrux/nitro-sniper-enhanced#9]
I am using hellbound's sniper and i realised that he/she deleted the repository and i ended up here. Is that version discontinued?
 i couldnt find anyway to contact him/her. I am switching to this one for now. Thank you for the work

**Comment by GiorgioBrux** [comment]
Hi,
You would need to ask him, I have no idea why s(he) decided to make his repo private or delete it. (never talked with him/her)
We are different people and these are different projects.

If you have further questions or encounter a bug/error feel free to open another issue.
