### ISSUE TITLE
Is my token safe on repit?

### ISSUE THREAD

**Issue by ItzMeAakash** [GiorgioBrux/nitro-sniper-enhanced#91]
Is my token safe on repit? I mean i dont have replit premium, I cant make the repl private so it will be public. Can someone else see my token there? because this is risky to deploy sniper on replit but i dont want to deploy sniper on herko cuz i keep logging out. Please tell is my token visible in that repl if i deploy on replit? (i cant make private repl..)

**Comment by GiorgioBrux** [comment]
If anyone knows the name of your replit and your username they can see your token, yes. You can kinda workaround it by having a completely random username/repl name.
