### ISSUE TITLE
an error occurs on replit - We couldn't reach your repl

### ISSUE THREAD

**Issue by nichevulcan20** [GiorgioBrux/nitro-sniper-enhanced#92]
I'm using uptime robot to ping the repl but still it is giving the error.. 
and the error is- 
**Hmmmm.... We Couldn't Reach Your Repl
Make sure your repl has a port open and is ready to receive HTTP traffic.**

this is the ss below-
![image](https://user-images.githubusercontent.com/81959998/117561826-c2490080-b0b7-11eb-8c20-ceb00ae354b5.png)

Also, i have set to use replit to true.

**Comment by GiorgioBrux** [comment]
It happens on my replit instance too and I have no idea why.
Will look into it asap.
