### ISSUE TITLE
Addapting to new update

### ISSUE THREAD

**Issue by Volas171** [GiorgioBrux/nitro-sniper-enhanced#95]
Discord changed the way they read messages, they now use a WebSocket for non bot users, therefore as the way it is currently it cant read messages.

**Comment by GiorgioBrux** [comment]
Still works on my end, doesn't it work for you?

**Comment by Volas171** [comment]
it kinda works as discord hasn't removed the API support yet but they will migrate to the WebSocket soon

**Comment by GiorgioBrux** [comment]
I know that api v6 is deprecated, I will try to move to an higher version asap. Anyway this is a discord.js issue, so I opened an issue there.

**Comment by Volas171** [comment]
understandable have a nice day

**Comment by GiorgioBrux** [comment]
Thanks for the heads up tho!

**Comment by Volas171** [comment]
no problem
